package core

const val NO_NETWORK = "Network connection required !"
internal const val MOCK_API_CERT = "mockapicert.crt"
const val GUEST_SIGNED_IN = "GUEST"
const val GITHUB_SIGNED_IN = "LOGGED IN : GITHUB"
const val GOOGLE_SIGNED_IN = "LOGGED IN : GOOGLE"
const val SITE_ID = "ditto"
var PDF_DOWNLOAD_URL : String ?= "";
//Shared Preference Keys
const val USER_EMAIL = "USER_EMAIL"
const val USER_PHONE = "USER_PHONE"
const val USER_FIRST_NAME = "USER_FIRST_NAME"
const val USER_LAST_NAME = "USER_LAST_NAME"
const val MIRROR_REMINDER = "MIRROR_REMINDER"
const val RECIEVER_EMAIL = "RECIEVER_EMAIL"
const val SPLICE_CUT_COMPLETE_REMINDER = "SPLICE_CUT_COMPLETE_REMINDER"
const val MULTIPLE_PIECE_REMINDER = "MULTIPLE_PIECE_REMINDER"
const val SPLICE_REMINDER = "SPLICE_REMINDER"
const val CUST_ID = "CUST_ID"
const val CUST_NO = "CUST_NO"
const val CONNECTED_SERVICE_NAME = "CONNECTED_SERVICE_NAME"
const val CONNECTED_SERVICE_HOST = "CONNECTED_SERVICE_HOST"
const val CONNECTED_SERVICE_PORT = "CONNECTED_SERVICE_PORT"
const val  CSUBSCRIPTION_ENDDATE="SUBSCRIPTION_ENDDATE"
const val  CSUBSCRIPTION_VALID="SUBSCRIPTION_VALID"
const val  CUSTOMERCARE_EMAIL="CUSTOMERCAREEMAIL"
const val  CUSTOMERCARE_PHONE="CUSTOMERCAREPHONE"
const val  CUSTOMERCARE_TIMING="CUSTOMERCARETIMING"
const val  VIDEO_URL="VIDEOURL"
const val SEARCH_COMPLETE = "SEARCH_COMPLETE"
const val SEARCH_COMPLETE_AFTER_WIFI = "SEARCH_COMPLETE_AFTER_WIFI"
const val MODE_SERVICE = "MODE_SERVICE"
const val MODE_BLE = "MODE_BLE"
const val SCREEN_MANAGE_DEVICE = "MD"

const val SUBSCRIPTION_VALID = "isvalid"
const val SUBSCRIPTION_START_DATE = "startdate"
const val SUBSCRIPTION_END_DATE = "enddate"
const val SUBSCRIPTION_PLAN_PRICE = "planprice"
const val SUBSCRIPTION_PLAN_NAME = "planname"
const val TRACKING_ID = "ZGl0dG9hbmRyb2lk"
const val PATTERN_COUNT = "COUNT"
const val TAILORNOVA_API_KEY_VALUE = "FA872702-6396-45DC-89F0-FC1BE900591B"
const val TAILORNOVA_API_KEY = "X-Api-Key"
const val OS = "Android"
const val CUSTOMER_EMAIL = "subscustomerOne@gmail.com"
const val UNKNOWN_HOST_EXCEPTION = "UnknownHostException !"
const val CONNECTION_EXCEPTION = "No Internet connection available !"
const val NO_SUCH_ELEMENT_EXCEPTION = "No such element exception"
var ERROR_FETCH = "Error Fetching data!"
const val HTTP_UNAUTHORIZED4="Unauthorized"
const val HTTP_INTERNAL_ERROR="Internal Server Error"
const val HTTP_BAD_REQUEST="Bad Request"
const val HTTP_FORBIDDEN="Forbidden Request"
const val EN_USERNAME="storefront"
const val EN_CPCODE="Testing4$"
const val AUTH="Basic "





