package com.ditto.login.domain

data class LoginUser(
    val userName: String?,
    val _type: String?="",
    val auth_type: String?="",
    val customer_id: String?="",
    val customer_no: String?="",
    val email: String?="",
    val first_name: String?="",
    val gender: Int?=0,
    val last_login_time: String?="",
    val last_modified: String?="",
    val phone_home: String?="",
    val last_name: String?="",
    val last_visit_time: String?="",
    val login: String?="",
    val previous_login_time: String?="",
    val previous_visit_time: String?="",
    val salutation: String?="",
    val isLoggedIn: Boolean? = false,
    val dndOnboarding: Boolean? = false,
    val bleDialogVisible: Boolean? = false,
    val wifiDialogVisible: Boolean? = false,
    val cMirrorReminder: Boolean? = false,
    val cReceiveEmail:Boolean? = false,
    val cSpliceCutCompleteReminder: Boolean? = false,
    val cSpliceMultiplePieceReminder: Boolean? = false,
    val cSpliceReminder: Boolean? = false,
    val cCuttingReminder: Boolean? = false,
    val cInterestArt: Boolean? = false,
    val cInterestBridalSpecialOccasionProjects: Boolean? = false,
    val cInterestClassroomCraftsDecor: Boolean? = false,
    val cInterestFloral: Boolean? = false,
    val cInterestFoodCrafts: Boolean? = false,
    val cInterestHolidayPartyDecorating: Boolean? = false,
    val cInterestHomeDecor: Boolean? = false,
    val cInterestJewelry: Boolean? = false,
    val cInterestKidsCrafts: Boolean? = false,
    val cInterestKnittingCrochet: Boolean? = false,
    val cInterestPaperCrafts: Boolean? = false,
    val cInterestQuiltingSewingFabric: Boolean? = false,
    val cIsCostumeGuildEnrolled: Boolean? = false,
    val cIsFourHEnrolled: Boolean? = false,
    val cIsGirlScoutsEnrolled: Boolean? = false,
    val cIsJoannPlusCustomer: Boolean? = false,
    val cIsMilitaryEnrolled: Boolean? = false,
    val cIsTaxExempt: Boolean? = false,
    val cIsTeacherEnrolled: Boolean? = false,
    val cLearnBrowseSocialMedia: Boolean? = false,
    val cLearnLookOnline: Boolean? = false,
    val cLearnTakeAClass: Boolean? = false,
    val cLearnVisitJoannStore: Boolean? = false,
    val cReceiveDirectMail: Boolean? = false,
    val cReceiveTextMessage: Boolean? = false,
    val cRegisteredWithNarvar: Boolean? = false,
    val cTaxExempt: Boolean? = false,
    val cInitialisationVector: String? = "",
    val cVectorKey: String? = ""


)