package com.ditto.login.domain.model

import com.ditto.login.domain.error.FaultDomain

data class LoginResultDomain(
    val _type: String?,
    val _v: String?,
    val authType: String?,
    val creationDate: String?,
    val customerId: String?,
    val customerNo: String?,
    val email: String?,
    val enabled: Boolean?,
    val firstName: String?,
    val gender: Int?,
    val lastLoginTime: String?,
    val lastModified: String?,
    val phoneHome: String?,
    val lastName: String?,
    val lastVisitTime: String,
    val login: String?,
    val previousLoginTime: String?,
    val previousVisitTime: String?,
    val salutation: String?,
    val faultDomain: FaultDomain?,
    val cMirrorReminder: Boolean,
    val cReceiveEmail: Boolean,
    val cSpliceCutCompleteReminder: Boolean,
    val cSpliceMultiplePieceReminder: Boolean,
    val cSpliceReminder: Boolean,
    val cCuttingReminder: Boolean,
    val cSaveCalibrationPhotos: Boolean,
    val cInterestArt: Boolean,
    val cInterestBridalSpecialOccasionProjects: Boolean,
    val cInterestClassroomCraftsDecor: Boolean,
    val cInterestFloral: Boolean,
    val cInterestFoodCrafts: Boolean,
    val cInterestHolidayPartyDecorating: Boolean,
    val cInterestHomeDecor: Boolean,
    val cInterestJewelry: Boolean,
    val cInterestKidsCrafts: Boolean,
    val cInterestKnittingCrochet: Boolean,
    val cInterestPaperCrafts: Boolean,
    val cInterestQuiltingSewingFabric: Boolean,
    val cIsCostumeGuildEnrolled: Boolean,
    val cIsFourHEnrolled: Boolean,
    val cIsGirlScoutsEnrolled: Boolean,
    val cIsJoannPlusCustomer: Boolean,
    val cIsMilitaryEnrolled: Boolean,
    val cIsTaxExempt: Boolean,
    val cIsTeacherEnrolled: Boolean,
    val cLearnBrowseSocialMedia: Boolean,
    val cLearnLookOnline: Boolean,
    val cLearnTakeAClass: Boolean,
    val cLearnVisitJoannStore: Boolean,
    val cReceiveDirectMail: Boolean,
    val cReceiveTextMessage: Boolean,
    val cRegisteredWithNarvar: Boolean,
    val cTaxExempt: Boolean,
    val cInitialisationVector: String,
    val cVectorKey: String,

    val cSubscriptionValid: Boolean,
    val cSubscriptionPlanEndDate: String?,
    val cSubscriptionStatus: String?,
    val cSubscriptionPlanStartDate: String?,
    val cSubscriptionPlanPrice: String?,
    val cSubscriptionPlanId: String?,
    val cSubscriptionPlanName: String?,
    val cSubscriptionID: String?,
    val cSubscriptionPlanCurrency: String?,
    val cSubscriptionType: String?,
    val cSubscriptionPlanBillingEndDate: String?,
    val cSubscriptionPlanBillingStartDate: String?,
    val cEncryptionkey:String?=""
)